import './globals.css';
import type { Metadata } from 'next';
import { Nanum_Gothic, Poppins } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;
import Header from './Header';
import 'styles/common.scss';
// import BubbleEffect from './BubbleEffect';

const poppins = Poppins({
  weight: ['400', '500', '600'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

const nanumGothic = Nanum_Gothic({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Country info',
  description: 'Generated by country info app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        {/* <BubbleEffect /> */}
      </body>
    </html>
  );
}
